### ISSUE TITLE
Error: Invalid BIP21 URI  at value (/Users/admin/bluewalletsecure/screen/send/details.js:87:11)

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#108]
Error: Invalid BIP21 URI: lightning:LNBC1500N1PDA9CDSPP5PDCJ7FWRKLDTU9GDK6D524AHSFMFH2PL42HKXMKSV4L4XKGXA87SDPA2FJKZEP6YPYX7AEQW3HJQEM9WSS8JMM4WGS8QCTED4JKUAPQVEEX7MFQ09SKCCQZYSXQR23SJAKU0FEXKUJZF7PJP7HPXSG0TPCJ08444DTA3QGX945MKL2XM6X897LSJG2T8K3DTAXTXF4EYSTASS9CYAEDTS6X4RUK8C4UW4QTSYGPSXYGFQ
  at value (/Users/admin/bluewalletsecure/screen/send/details.js:87:11)
  at _this2 (/Users/admin/bluewalletsecure/events.js:11:45)
  at None (/Users/admin/bluewalletsecure/screen/send/scanQrAddress.js:23:7)
  at onBarCodeScanned (/Users/admin/bluewalletsecure/screen/send/scanQrAddress.js:16:26)
  at lastEventsTimes (/Users/admin/bluewalletsecure/screen/send/scanQrAddress.js:52:47)
...
(28 additional frame(s) were not displayed)

**Comment by Overtorment** [comment]
@marcosrdz can u handle this one?

**Comment by marcosrdz** [comment]
Fixed 253e28f64c391ce55c9b7fc9921b4392588f62e1
