### ISSUE TITLE
error Failed to install the app. Make sure you have the Android development environment

### ISSUE THREAD

**Issue by ChayanonSaelee** [BlueWallet/BlueWallet#4416]
## error Failed to install the app. Make sure you have the Android development environment

Please provide:
* phone model realme7 ( android11 )
* node version ( v14.17.3 )
* window 10

## Error
this is error when I run "npx react-native run-android".

```
> Task :app:checkDebugAarMetadata FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9.2/userguide/command_line_interface.html#sec:command_line_warnings
56 actionable tasks: 2 executed, 54 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.sqlite:sqlite-framework:2.2.0.
     AAR metadata file: C:\Users\NeayNie\.gradle\caches\transforms-3\f5a0ade1653c808a85dcfa7d197c25c2\transformed\sqlite-framework-2.2.0\META-INF\com\android\build\gradle\aar-metadata.properties.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.sqlite:sqlite-framework:2.2.0.
     AAR metadata file: C:\Users\NeayNie\.gradle\caches\transforms-3\f5a0ade1653c808a85dcfa7d197c25c2\transformed\sqlite-framework-2.2.0\META-INF\com\android\build\gradle\aar-metadata.properties.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

    at makeError (D:\LndHub\BlueWallet\node_modules\execa\index.js:174:9)
    at D:\LndHub\BlueWallet\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (D:\LndHub\BlueWallet\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (D:\LndHub\BlueWallet\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:186:9)
info Run CLI with --verbose flag for more details.
```
### file build.gradle
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        minSdkVersion = 28
        supportLibVersion = "28.0.0"
        buildToolsVersion = "30.0.3"
        compileSdkVersion = 30
        targetSdkVersion = 30
        googlePlayServicesVersion = "16.+"
        googlePlayServicesIidVersion = "16.0.1"
        firebaseVersion = "17.3.4"
        firebaseMessagingVersion = "20.2.1"
        ndkVersion = "23.0.7599858"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:4.2.2')
        classpath("com.bugsnag:bugsnag-android-gradle-plugin:5.+")
        classpath 'com.google.gms:google-services:4.3.10'  // Google Services plugin


        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter() {
            content {
                includeModule("com.facebook.yoga", "proguard-annotations")
                includeModule("com.facebook.fbjni", "fbjni-java-only")
                includeModule("com.facebook.fresco", "fresco")
                includeModule("com.facebook.fresco", "stetho")
                includeModule("com.facebook.fresco", "fbcore")
                includeModule("com.facebook.fresco", "drawee")
                includeModule("com.facebook.fresco", "imagepipeline")
                includeModule("com.facebook.fresco", "imagepipeline-native")
                includeModule("com.facebook.fresco", "memory-type-native")
                includeModule("com.facebook.fresco", "memory-type-java")
                includeModule("com.facebook.fresco", "nativeimagefilters")
                includeModule("com.facebook.stetho", "stetho")
                includeModule("com.wei.android.lib", "fingerprintidentify")
            }
        }
        mavenCentral()
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        maven {
            // All of Detox' artifacts are provided via the npm module
            url "$rootDir/../node_modules/detox/Detox-android"
        }
        google()
                maven { url 'https://www.jitpack.io' }
    }
}

subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 30
                buildToolsVersion '30.0.3'
                 defaultConfig {
                    minSdkVersion 28
                }
            }
        }
    }
}
```

**Comment by marcosrdz** [comment]
We use macOS and Linux for development. Windows has not been compiled against.

**Comment by ChayanonSaelee** [comment]
> Can I use Windows Subsystem for Linux (WSL) for compile ? or can you recommend any other method?

**Comment by marcosrdz** [comment]
I'd be lying if I list anything out since none of our environments contain Windows.

**Comment by BenGWeeks** [comment]
Did you get this to build on Windows out of interest @ChayanonSaelee?

**Comment by BenGWeeks** [comment]
Here are my notes on getting this to run (as far as I can) on Windows that offers may find useful.

Ensure you add`"C:\Users\USERNAME\AppData\Local\Android\sdk\platform-tools` to your PATH in Environment Variables.

Ensure that you have `Android 12.0 (s)` (API level: 31) installed in Android Studio (`Tools` > `Appearance & Behaviour` > `System Settings` > `Android SDK`).

When creating a device, choose Release Name "S" (you may need to download this).

You may also need to change `File` > `Settings` > `Build, Execution, Deployment` > `Build Tools` > `Gradle` where it says `Gradle JDK` from `Android Studio default JDK` to `corretto-11`. (You may need to Download it then add it using Java Control Panel)

Add the location you installed it to (e.g. `C:\Users\USERNAME\.jdks\corretto-11.0.17`) as a System Environment variable for `JAVA_Home`.

Run the following:

```
Npm install jsc-android
```

Add the following packaging options to line 165 of `build.gradle` (:app):

```
  packagingOptions {
    pickFirst 'lib/x86_64/libjsc.so'
    pickFirst 'lib/arm64-v8a/libjsc.so'
  }
```

Download Watchman from [Installation | Watchman (facebook.github.io)](http://facebook.github.io/watchman/docs/install.html).

Extract and add the path to the bin folder to Environment Variables (e.g. `X:\watchman-v2022.11.14.00-windows\bin`)

Add the following to `metro.config.js` (line 18):

```
    sourceExts: ['js', 'jsx', 'ts', 'tsx', 'cjs', 'json']
```

Open `Git Bash` and run:

```
./release-notes.sh
```

Now delete the contents of `node_modules` (if it contains anything). Close and re-open the CMD Window (as an Administrator) if you have it open. Then re-run:

```
Watchman watch-del-all
Npm install
Rm -rf /tmp/metro-*
Npx react-native run-android
```

However, I am stuck at this point (so above is certainly not a complete resolution):

[https://github.com/BlueWallet/BlueWallet/issues/5201](https://github.com/BlueWallet/BlueWallet/issues/5201)
