### ISSUE TITLE
Compilation fails with error Unable to resolve module realm/realm-constants.json

### ISSUE THREAD

**Issue by Giszmo** [BlueWallet/BlueWallet#5813]
I'm trying to compile using a docker.io/node:16.20.0-bullseye-slim container and it fails with

```
> Task :app:createBundleReleaseJsAndAssets
warning: the transform cache was reset.
                Welcome to Metro v0.73.10
              Fast - Scalable - Integrated


warn Package react-native-fingerprint-scanner contains invalid configuration: "dependency.assets" is not allowed,"dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
error Unable to resolve module realm/realm-constants.json from /Users/runner/work/1/s/node_modules/realm/dist/bundle.react-native.js: realm/realm-constants.json could not be found within the project or in these directories:
  node_modules
  4 | var reactNative = require('react-native');
  5 | var bson = require('bson');
> 6 | var realmConstants_json = require('realm/realm-constants.json');
    |                                    ^
  7 |
  8 | function _interopNamespaceDefault(e) {
  9 |   var n = Object.create(null);
Error: Unable to resolve module realm/realm-constants.json from /Users/runner/work/1/s/node_modules/realm/dist/bundle.react-native.js: realm/realm-constants.json could not be found within the project or in these directories:
  node_modules
  4 | var reactNative = require('react-native');
  5 | var bson = require('bson');
> 6 | var realmConstants_json = require('realm/realm-constants.json');
    |                                    ^
  7 |
  8 | function _interopNamespaceDefault(e) {
  9 |   var n = Object.create(null);
    at ModuleResolver.resolveDependency (/Users/runner/work/1/s/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:162:15)
    at DependencyGraph.resolveDependency (/Users/runner/work/1/s/node_modules/metro/src/node-haste/DependencyGraph.js:260:43)
    at Object.resolve (/Users/runner/work/1/s/node_modules/metro/src/lib/transformHelpers.js:177:21)
    at Graph._resolveDependencies (/Users/runner/work/1/s/node_modules/metro/src/DeltaBundler/Graph.js:432:35)
    at Graph._processModule (/Users/runner/work/1/s/node_modules/metro/src/DeltaBundler/Graph.js:218:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Graph._addDependency (/Users/runner/work/1/s/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
    at async Promise.all (index 0)
    at async Graph._processModule (/Users/runner/work/1/s/node_modules/metro/src/DeltaBundler/Graph.js:263:5)
    at async Graph._addDependency (/Users/runner/work/1/s/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
```

I think this is related to https://github.com/realm/realm-js/issues/6204 and I'm trying to work around this accordingly.

**Comment by Overtorment** [comment]
dont know what to say. everything builds on my machine, other devs machines, on several CIs.
