### ISSUE TITLE
Cannot read property 'HDSegwitBech32Wallet' of undefined

### ISSUE THREAD

**Issue by Bamskki** [BlueWallet/BlueWallet#6070]
I'm trying to run BW and whenever I try to create a Bitcoin wallet, it gives me this error: "TypeError: undefined is not a function, js engine: hermes
 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'HDSegwitBech32Wallet' of undefined
TypeError: Cannot read property 'HDSegwitBech32Wallet' of undefined
    at ?anon_0_ (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:362740:68)
    at next (native)
    at asyncGeneratorStep (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:5869:26)
    at _next (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:5888:29)
"

**Comment by marcosrdz** [comment]
Please provide details such as environment and if you have the latest code from master. Im unable to replicate

**Comment by Bamskki** [comment]
I'm working on this branch https://github.com/Cypher-Elves/Cypher-Bank

Mac M1
Node version v20.11.0
Npm version 10.2.4
Pod version 1.14.3

Full log (running app and creating Bitcoin wallet)
```BUNDLE  ./index.js 

 WARN  Require cycle: components/TooltipMenu.ios.js -> components/QRCodeComponent.tsx -> components/TooltipMenu.ios.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 LOG  Running "BlueWallet" with {"rootTag":1,"initialProps":{}}
 LOG  Privacy blur: true
 LOG  updating exchange rate...
 LOG  getIsTorCapable true
 LOG  Apple Watch: isInstalled: false, isReachable: false, walletsInitialized: false
 LOG  begin connection: {"host":"bitcoin.lukechilds.co","ssl":"50002"}
 LOG  TLS Connected to  bitcoin.lukechilds.co 50002
 LOG  connected to  ["ElectrumX 1.16.0", "1.4"]
 LOG  Biometrics isDeviceBiometricCapable failed
 LOG  [FingerprintScannerNotEnrolled: Authentication could not start because Fingerprint Scanner has no enrolled fingers.]
 WARN  error reading data_encrypted {"message":"key does not present"}
 WARN  fallback to realm
 LOG  startAndDecrypt
 WARN  error reading data_encrypted {"message":"key does not present"}
 WARN  fallback to realm
 WARN  error reading data {"message":"key does not present"}
 WARN  fallback to realm
 LOG  Apple Watch: isInstalled: false, isReachable: false, walletsInitialized: true
 WARN  Battery state `unknown` and monitoring disabled, this is normal for simulators and tvOS.
 LOG  No userActivity object sent
 WARN  error reading data_encrypted {"message":"key does not present"}
 WARN  fallback to realm
 WARN  error reading data_encrypted {"message":"key does not present"}
 WARN  fallback to realm
 LOG  fetchSenderPaymentCodes for wallet# false
 LOG  fetch payment codes took 0.001 sec
 LOG  fetchWalletBalances for wallet# false
 LOG  fetch balance took 0 sec
 LOG  fetchWalletTransactions for wallet# false
 LOG  fetch tx took 0 sec
 LOG  not saving empty wallets array
 ERROR  TypeError: undefined is not a function, js engine: hermes
 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'HDSegwitBech32Wallet' of undefined
TypeError: Cannot read property 'HDSegwitBech32Wallet' of undefined
    at ?anon_0_ (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:362740:68)
    at next (native)
    at asyncGeneratorStep (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:5869:26)
    at _next (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:5888:29)
    at anonymous (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:5893:14)
    at tryCallTwo (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:5885:25)
    at apply (native)
    at createWallet (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:362779:26)
    at _performTransitionSideEffects (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:51877:22)
    at _receiveSignal (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:51833:45)
    at onResponderRelease (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:51700:34)
    at apply (native)
    at invokeGuardedCallbackProd (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:63534:21)
    at apply (native)
    at invokeGuardedCallback (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:63620:42)
    at apply (native)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:63623:36)
    at executeDispatch (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:63687:48)
    at executeDispatchesInOrder (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:63704:26)
    at executeDispatchesAndRelease (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:64810:35)
    at executeDispatchesAndReleaseTopLevel (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:64817:43)
    at forEach (native)
    at forEachAccumulated (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:64146:22)
    at runEventsInBatch (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:64828:27)
    at runExtractedPluginEventsInBatch (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:64887:25)
    at anonymous (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:64868:42)
    at batchedUpdates$1 (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:75458:20)
    at batchedUpdates (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:64799:36)
    at _receiveRootNodeIDEvent (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:64867:23)
    at receiveTouches (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:64910:34)
    at apply (native)
    at __callFunction (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:7137:36)
    at anonymous (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:6897:31)
    at __guard (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:7087:15)
    at callFunctionReturnFlushedQueue (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=io.bluewallet.bluewallet:6896:21) ```

**Comment by Overtorment** [comment]
its hard to tell whats the problem since the fork is 8619 commits behind..?

![image](https://github.com/BlueWallet/BlueWallet/assets/1913337/760ded54-4704-4f7b-89b4-cb92fdbe1ac9)

**Comment by Overtorment** [comment]
i doubt we can be of any help here
