### ISSUE TITLE
Stuck on blank screen on Android fresh install

### ISSUE THREAD

**Issue by canselcik** [BlueWallet/BlueWallet#708]
Hi,

I see that this issue has been brought up before but with no conclusive resolution. I am currently running the build from the Play Store. If the code here is more recent, I can build and give it a try. Otherwise, just letting you know that this issue is affecting a fresh Pixel 4 install.

Thanks.

**Comment by ncoelho** [comment]
Hi @canselcik do you have time to look into this. It would help a lot

**Comment by canselcik** [comment]
@ncoelho I will launch the application today while connected to my machine and I'll provide some logcat output. Hopefully that'll help us find a solution.

**Comment by ncoelho** [comment]
cc @marcosrdz

**Comment by canselcik** [comment]
@ncoelho @marcosrdz 

From the logcat output, I have a feeling it might be due to this:
```
10-27 14:54:09.904 28324 28392 W System.err: java.io.FileNotFoundException: /data/user/0/io.bluewallet.bluewallet/files/SKS_KEY_FILEdata_encrypted: open failed: ENOENT (No such file or directory)
10-27 14:54:09.904 28324 28392 W System.err: 	at libcore.io.IoBridge.open(IoBridge.java:496)
10-27 14:54:09.904 28324 28392 W System.err: 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
10-27 14:54:09.904 28324 28392 W System.err: 	at android.app.ContextImpl.openFileInput(ContextImpl.java:600)
10-27 14:54:09.904 28324 28392 W System.err: 	at android.content.ContextWrapper.openFileInput(ContextWrapper.java:206)
10-27 14:54:09.904 28324 28392 W System.err: 	at android.content.ContextWrapper.openFileInput(ContextWrapper.java:206)
10-27 14:54:09.904 28324 28392 W System.err: 	at com.reactlibrary.securekeystore.Storage.readValues(Storage.java:21)
10-27 14:54:09.904 28324 28392 W System.err: 	at com.reactlibrary.securekeystore.RNSecureKeyStoreModule.getSymmetricKey(RNSecureKeyStoreModule.java:189)
10-27 14:54:09.904 28324 28392 W System.err: 	at com.reactlibrary.securekeystore.RNSecureKeyStoreModule.getPlainText(RNSecureKeyStoreModule.java:194)
10-27 14:54:09.904 28324 28392 W System.err: 	at com.reactlibrary.securekeystore.RNSecureKeyStoreModule.get(RNSecureKeyStoreModule.java:146)
10-27 14:54:09.904 28324 28392 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
10-27 14:54:09.904 28324 28392 W System.err: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
10-27 14:54:09.904 28324 28392 W System.err: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
10-27 14:54:09.904 28324 28392 W System.err: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
10-27 14:54:09.904 28324 28392 W System.err: 	at android.os.Handler.handleCallback(Handler.java:883)
10-27 14:54:09.904 28324 28392 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:100)
10-27 14:54:09.904 28324 28392 W System.err: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
10-27 14:54:09.904 28324 28392 W System.err: 	at android.os.Looper.loop(Looper.java:214)
10-27 14:54:09.904 28324 28392 W System.err: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
10-27 14:54:09.904 28324 28392 W System.err: 	at java.lang.Thread.run(Thread.java:919)
10-27 14:54:09.905 28324 28392 W System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
10-27 14:54:09.905 28324 28392 W System.err: 	at libcore.io.Linux.open(Native Method)
10-27 14:54:09.905 28324 28392 W System.err: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
10-27 14:54:09.905 28324 28392 W System.err: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
10-27 14:54:09.905 28324 28392 W System.err: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
10-27 14:54:09.905 28324 28392 W System.err: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7255)
10-27 14:54:09.905 28324 28392 W System.err: 	at libcore.io.IoBridge.open(IoBridge.java:482)
10-27 14:54:09.905 28324 28392 W System.err: 	... 18 more
```

Here is the full logcat output for the launch of Blue Wallet:
https://gist.github.com/canselcik/a0a8f46a7a785339c4b97a334e2ddb3e

**Comment by marcosrdz** [comment]
I’ll code in some additional safeguards against the messages in the log. This might be a guessing game since I’m unable to replicate the issue. Hopefully the safeguards will fix the bug.

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/713

**Comment by canselcik** [comment]
Confirmed fixed by https://github.com/BlueWallet/BlueWallet/pull/713.

**Comment by Overtorment** [comment]
Glad it worked out
